### PR TITLE
Fix test failures

### LINKED ISSUE #118: Database Error in test relationships_visit_occurrence_provider_id__provider_id__ref_provider_
## What 

error when building the dbt_synthea using Postgres
error is related to adding an explicit cast but unable to identify the test case (please see screenshot)

Image

### PR DESCRIPTION
**Pull request by katy-sadowski**
Fixes #118 and #119 

There were 2 separate issues leading to PK duplication in PROCEDURE_OCCURRENCE:

- Something was messed up in the inpatient visit rollup logic
- There are duplicated encounter IDs in the source Synthea tables (a known bug)

For the first, I did a deep review of the IP rollup logic and fixed some issues with it.  I left a lot of comments because until now I didn't fully understand what it was doing (this came from ETL-Synthea).  I figure my comments may help others who want to understand or need to debug.

For the second, my solution was to remove these encounters from the project altogether.  Since there are other Synthea tables with foreign keys to the encounters table, I think this is the only way to handle the issue - I think it's better to lose the data than to incorrectly assign an encounter to a different encounter/patient's procedure/diagnosis/etc.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -10,4 +10,5 @@ data/
 .Rhistory
 *.duckdb
 .dbt/
-profiles.yml
\ No newline at end of file
+profiles.yml
+.vscode/mcp.json
```
Comment (lawrenceadams) [inline .gitignore:14]: By-the-by have you found the MCP server stuff useful?

File: models/intermediate/int__ip_visits.sql
Comment (lawrenceadams) [inline models/intermediate/int__ip_visits.sql:1]: Complex one! Nice! I think I can track the flow clearly - and tests are all good

**Review by lawrenceadams — APPROVED** [review]

File: .gitignore (hunk 1 above)
Comment (katy-sadowski) [reply .gitignore:14]: I haven't tried anything with it yet! I think this file got added when I installed or upgraded something.

**Comment by katy-sadowski** [comment]
Thanks so much for your review @lawrenceadams !
